// <auto-generated />
using ManipulaImagem.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace ManipulaImagem.Migrations
{
    [DbContext(typeof(ManipulaImagemContext))]
    [Migration("20180506003848_CriacaoBanco")]
    partial class CriacaoBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("ManipulaImagem.DataBase.Acao", b =>
                {
                    b.Property<int>("ManipulacaoId");

                    b.Property<int>("Ordem");

                    b.Property<int>("Tipo");

                    b.HasKey("ManipulacaoId", "Ordem");

                    b.ToTable("Acao");

                    b.HasDiscriminator<int>("Tipo");
                });

            modelBuilder.Entity("ManipulaImagem.DataBase.Manipulacao", b =>
                {
                    b.Property<int>("ManipulacaoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("ManipulacaoId");

                    b.ToTable("Manipulacao");
                });

            modelBuilder.Entity("ManipulaImagem.DataBase.AcaoEscala", b =>
                {
                    b.HasBaseType("ManipulaImagem.DataBase.Acao");

                    b.Property<int>("Percentagem");

                    b.ToTable("Acao");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("ManipulaImagem.DataBase.AcaoRotacao", b =>
                {
                    b.HasBaseType("ManipulaImagem.DataBase.Acao");

                    b.Property<int>("Angulo");

                    b.ToTable("Acao");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("ManipulaImagem.DataBase.AcaoTranslacao", b =>
                {
                    b.HasBaseType("ManipulaImagem.DataBase.Acao");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.ToTable("Acao");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("ManipulaImagem.DataBase.Acao", b =>
                {
                    b.HasOne("ManipulaImagem.DataBase.Manipulacao", "Manipulacao")
                        .WithMany("Acoes")
                        .HasForeignKey("ManipulacaoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
